version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: .
    volumes:
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: bulletin_board
    ports:
      - "6603:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: